// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: garages_users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGargeUserRelation = `-- name: CreateGargeUserRelation :one
INSERT INTO garages_users(garage_id, user_id, is_admin,created_at,updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING garage_id, user_id, is_admin, created_at, updated_at
`

type CreateGargeUserRelationParams struct {
	GarageID  pgtype.UUID
	UserID    pgtype.UUID
	IsAdmin   bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) CreateGargeUserRelation(ctx context.Context, arg CreateGargeUserRelationParams) (GaragesUser, error) {
	row := q.db.QueryRow(ctx, createGargeUserRelation,
		arg.GarageID,
		arg.UserID,
		arg.IsAdmin,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GaragesUser
	err := row.Scan(
		&i.GarageID,
		&i.UserID,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
