// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Car struct {
	ID           pgtype.UUID
	GarageID     pgtype.UUID
	LicensePlate string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type Garage struct {
	ID         pgtype.UUID
	GarageName string
	DeviceID   pgtype.UUID
	GestureSeq pgtype.Text
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	VideoUrl   pgtype.Text
}

type GaragesUser struct {
	GarageID  pgtype.UUID
	UserID    pgtype.UUID
	IsAdmin   bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID        pgtype.UUID
	Username  string
	PassHash  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
