services:
  server:
    ports:
      - 443:443
      - 444:444
      - 9001:9001
    build: 
      context: .
      dockerfile: server.Dockerfile
    environment:
      PG_URL: database-1.cluster-c70c2oyg0r3c.ca-central-1.rds.amazonaws.com
    depends_on:
      db:
        condition: service_healthy
        restart: true

#   db:
#     image: postgres:17.4
#     environment:
#       POSTGRES_USER: ${PG_ADMIN}
#       POSTGRES_DB: ${PG_DB_NAME}
#       POSTGRES_PASSWORD: ${PG_ADMIN_PASSWORD}
#     volumes:
#       - "db:/var/lib/postgresql/data"
#     ports:
#       - 5432:5432
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U ${PG_ADMIN} -d ${PG_DB_NAME}"]

# volumes:
#   db:

    